# ============================================================================
# Generic Deep Validation Configuration Template
# ============================================================================
# Use this AFTER running exploratory mode to validate your winners
# Copy the winning configuration from your exploratory results
# ============================================================================

mode: deep
repetitions: 10

model_path: /path/to/your/model.gguf
model_info: "model-name-Q4_K_M"

# Deep mode: only test the winning build
builds:
  winning_build:
    binary: /path/to/winning/llama-bench
    label: "Winner from exploratory"

builds_select:
  - winning_build

# Test matrix - use ONLY the winning config from exploratory
test_matrix:
  # Example: If "all_cores" won in exploratory, validate it here
  - name: "winner_config"
    numactl: "--physcpubind=<winning_cores>"  # Copy from exploratory winner
    env:
      OMP_NUM_THREADS: "<thread_count>"
    extra_args: "-t <thread_count>"

# Same metrics as exploratory
metrics:
  - pp512
  - tg128
  - mixed

# Output directory
output_dir: ./reports
