# ============================================================================
# Minimal Quick-Start Configuration
# ============================================================================
# Copy this to test.yaml and customize the 3 sections below
# ============================================================================

mode: exploratory
repetitions: 2

# 1. SET YOUR MODEL PATH
model_path: /path/to/your/model.gguf
model_info: "MyModel-Q4_K_M"

# 2. SET YOUR BUILD PATH
builds:
  my_build:
    binary: /path/to/llama-bench
    label: "My Build"

builds_select:
  - my_build

# 3. SET YOUR CPU CORES (use: lscpu --parse=CPU,Core,Node)
test_matrix:
  - name: "test_run"
    numactl: "--physcpubind=0,1,2,3,4,5,6,7"  # CHANGE: your physical cores
    env:
      OMP_NUM_THREADS: "8"  # CHANGE: match your core count
    extra_args: "-t 8"  # CHANGE: match your core count

# Standard metrics
metrics:
  - pp512
  - tg128

# Output
output_dir: ./reports
